# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20181020_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
