# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_inst_institutions_programeducationalobjectives_sttudentoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inst',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.Institutions'),
        ),
    ]
