# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20181109_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inst',
            new_name='Item',
        ),
    ]
