# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_auto_20181109_1938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemInstitution',
        ),
        migrations.RenameModel(
            old_name='sttudentOutcome',
            new_name='studentOutcome',
        ),
    ]
