# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_auto_20181109_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemInstitution',
            new_name='Item',
        ),
    ]
