# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_auto_20181109_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentoutcome',
            old_name='sttudentOutcome',
            new_name='studentOutcome',
        ),
        migrations.AlterField(
            model_name='programeducationalobjectives',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.Item'),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.Item'),
        ),
    ]
