# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0013_auto_20181112_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='confirm_password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='mission',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='state',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='street',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='zipcode',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='programeducationalobjectives',
            name='objective',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='studentoutcome',
            name='studentOutcome',
            field=models.TextField(default=''),
        ),
    ]
